### ISSUE TITLE
Nice use of callbacks when making requests!

### ISSUE THREAD

**Issue by TMMeijers** [yasershomaf/HomeWorks#2]
Great, even better would be to make the first argument `err` contain the actuall error or error message. So every function that needs a response can handle the error in it's own way. 

Note that XmlHTTPRequest also has the `onload` and `onerror` events which might be even more useful since you don't have to check for the property `message`.

Overal, very good work!

**Comment by yasershomaf** [comment]
I did that using .catch in promises
